version: '2'
services: 
  db:
    image: mysql/mysql-server:5.7
    ports: 
      - "3305:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root" 
      - "MYSQL_DATABASE=currencyrates" 
  cli:
    build: .
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - "db:database"

